-- MySQL Script generated by MySQL Workbench
-- Sun Dec 20 12:43:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CoronaHealthcare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CoronaHealthcare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoronaHealthcare` DEFAULT CHARACTER SET utf8 ;
USE `CoronaHealthcare` ;

-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zip` VARCHAR(5) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`profil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`profil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `adress` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profil_adress_idx` (`adress` ASC),
  CONSTRAINT `fk_profil_adress`
    FOREIGN KEY (`adress`)
    REFERENCES `CoronaHealthcare`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ordercol` VARCHAR(45) NULL,
  `profil` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_profil1_idx` (`profil` ASC),
  CONSTRAINT `fk_order_profil1`
    FOREIGN KEY (`profil`)
    REFERENCES `CoronaHealthcare`.`profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  `description` VARCHAR(255) NULL DEFAULT 'Zu diesem Produkt gibt es noch keine Beschreibung.',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`orderHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`orderHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `change` VARCHAR(100) NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderHistory_order1_idx` (`order` ASC),
  CONSTRAINT `fk_orderHistory_order1`
    FOREIGN KEY (`order`)
    REFERENCES `CoronaHealthcare`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`orderProductMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`orderProductMapping` (
  `products_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `order_id`),
  INDEX `fk_products_has_order_order1_idx` (`order_id` ASC),
  INDEX `fk_products_has_order_products1_idx` (`products_id` ASC),
  CONSTRAINT `fk_products_has_order_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `CoronaHealthcare`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `CoronaHealthcare`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
