-- MySQL Script generated by MySQL Workbench
-- Mon Dec 21 11:40:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CoronaHealthcare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CoronaHealthcare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CoronaHealthcare` DEFAULT CHARACTER SET utf8 ;
USE `CoronaHealthcare` ;

-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `zip` VARCHAR(5) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_adress_idx` (`address` ASC),
  CONSTRAINT `fk_profile_adress`
    FOREIGN KEY (`address`)
    REFERENCES `CoronaHealthcare`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `profile` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_profil1_idx` (`profile` ASC),
  CONSTRAINT `fk_order_profile1`
    FOREIGN KEY (`profile`)
    REFERENCES `CoronaHealthcare`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  `description` VARCHAR(255) NULL DEFAULT 'Zu diesem Produkt gibt es noch keine Beschreibung.',
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`orderHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`orderHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `change` VARCHAR(100) NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orderHistory_order1_idx` (`order` ASC),
  CONSTRAINT `fk_orderHistory_order1`
    FOREIGN KEY (`order`)
    REFERENCES `CoronaHealthcare`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `CoronaHealthcare`.`orderProductMapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CoronaHealthcare`.`orderProductMapping` (
  `product_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `order_id`),
  INDEX `fk_product_has_order_order1_idx` (`order_id` ASC),
  INDEX `fk_product_has_order_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_product_has_order_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `CoronaHealthcare`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_order_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `CoronaHealthcare`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
